### ISSUE TITLE
Error while get mac address

### ISSUE THREAD

**Issue by k03mad** [suskind/network-list#1]
Hello,

I faced with error at getting mac address from my Raspberry Pi 3.

```
/node_modules/network-list/lib/index.js:45
                        result.mac = mac.replace(/:([^:]{1}):/g, ':0$1:');
                                         ^

TypeError: Cannot read property 'replace' of undefined
    at /node_modules/network-list/lib/index.js:45:42
    at ChildProcess.<anonymous> (/home/pi/git/raspi-tlgrm-bot/node_modules/node-arp/lib/arp.js:73:5)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:159:13)
    at Pipe._handle.close [as _onclose] (net.js:558:12)
```

It happens, then RPi try to get mac from RPi current ip.
I made quick fix at the fork and now it works for me:
https://github.com/k03mad/network-list/commit/a0f53e2b5af882a3f0cb8bcceafdc3d5ed70c39f

Here https://github.com/suskind/network-list/blob/master/src/index.js#L42 must be an error.
But it's not.

**Comment by suskind** [comment]
Hi, 

I see. 

Unfortunately I don't have any linux here to try it now. But I confess that when I made this module only tested it on OSX. 

Your fix looks good for me, if you want you can make a pull request with your fix. 

Thank you

**Comment by k03mad** [comment]
Thanks!

**Comment by suskind** [comment]
published 

thanks again
